/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MainJFrame;

import data.AESFileEncryptor;
import data.Working;
import java.awt.Desktop;
import java.beans.PropertyChangeEvent;
import java.io.File;
import java.io.IOException;
import model.FileModel;

/**
 *
 * @author ahmad
 */
public class FileItem extends javax.swing.JPanel {

    private FileModel fileModel;
    private MainViewModel mainViewModel;
    private boolean readyToOpen;
    private boolean canOpen;

    public FileItem() {
        initComponents();
    }

    public FileItem(FileModel fileModel) {
        initComponents();
        mainViewModel = new MainViewModel();
        this.fileModel = fileModel;

        if (this.fileModel != null) {
            jLabelName.setText(fileModel.file_name);
            jLabelSender.setText(fileModel.extension);
            jLabelSize.setText(fileModel.file_size + " بايت");
            jLabelName.setText(fileModel.file_name);
            jLabelDate.setText(fileModel.getCreateDate());
            jProgressBar1.setValue(0);

        }

        mainViewModel.working.observe((PropertyChangeEvent evt) -> {
            Working working = (Working) evt.getNewValue();
            if (working.isRunning()) {
                cusButton1.setText(working.getsSmg());
            } else if (working.isSuccessful()) {
                cusButton1.setText("فك تشفير");
                readyToOpen = true;
                canOpen = false;
            } else {
                readyToOpen = false;
                canOpen = false;
                cusButton1.setText("تنزيل");
            }
            cusButton1.setEnabled(!working.isRunning());
        });

        mainViewModel.progressValueLiveData.observe((PropertyChangeEvent evt) -> {
            Integer integer = (Integer) evt.getNewValue();
            if (integer != null) {
                jProgressBar1.setValue(integer);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelSender = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        cusButton1 = new data.CusButton();
        jLabelDate = new javax.swing.JLabel();

        jProgressBar1.setValue(50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-file-100.png"))); // NOI18N

        jLabelName.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 20)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelName.setText("اسم الملف");

        jLabelSender.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelSender.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSender.setText("نوع الملف");

        jLabelSize.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSize.setText("حجم الملف");

        cusButton1.setForeground(new java.awt.Color(255, 255, 255));
        cusButton1.setText("تنزيل");
        cusButton1.setColor(data.MyColor.BackColor);
        cusButton1.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 14)); // NOI18N
        cusButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cusButton1.setRadius(40);
        cusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusButton1ActionPerformed(evt);
            }
        });

        jLabelDate.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDate.setText("تاريخ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabelSize, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelSender, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSender)
                                    .addComponent(jLabelSize)))
                            .addComponent(cusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusButton1ActionPerformed
        // TODO add your handling code here:
        if (mainViewModel.working.getValue().isRunning()) {
            return;
        }
        if (!readyToOpen) {
            mainViewModel.downloadFile(this.fileModel);
        } else if (!canOpen) {
            try {
                AESFileEncryptor fileEncryptor = new AESFileEncryptor();
                File file = new File(fileModel.getFileAllName());
                File decryptedFile = new File(file.getName());
                fileEncryptor.decryptFile(this.fileModel.scert_key, file, decryptedFile);
                cusButton1.setText("فتح");
                canOpen = true;
            } catch (Exception ex) {
                System.getLogger(FileItem.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        } else {
            
            if (Desktop.isDesktopSupported()) {
                try {
                    File file = new File(fileModel.getFileAllName());
                    Desktop.getDesktop().open(file);
                    mainViewModel.file_received(fileModel.file_id);
                } catch (IOException ex) {
                    System.err.println(ex.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_cusButton1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private data.CusButton cusButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSender;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
