/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.MainJFrame;

import data.ClientAPI;
import data.Working;
import io.socket.client.Socket;
import java.awt.ComponentOrientation;
import java.beans.PropertyChangeEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.FileModel;
import model.UserModel;
import ui.Dialog.NotificationDialog;
import ui.FileSendJDialog.FileSendJDialog;
import ui.SendFileJDialog.SendFileJDialog;

/**
 *
 * @author ahmad
 */
public class MainJFrame extends javax.swing.JFrame {

    private int x, y;
    private final UserModel userModel;
    private MainViewModel mainViewModel;

    public MainJFrame(UserModel model) {
        initComponents();
        this.userModel = model;

        if (userModel != null) {
            jLabel1.setText(model.user_name);
            jLabel2.setText(model.center_name);
            this.mainViewModel = new MainViewModel(model);
            jPanelFiles.removeAll();
            jPanelFiles.revalidate();
            jPanelFiles.repaint();
        }

        mainViewModel.working.observe((PropertyChangeEvent evt) -> {
            Working working = (Working) evt.getNewValue();
            stateParProgress.setBusy(working.isRunning());
            stateParProgress.setVisible(working.isRunning());
            stateParMsg.setText(working.getsSmg());
            stateParMsg.setForeground(working.getColor());
            cusButton1.setEnabled(!working.isRunning());
        });

        MainViewModel.filesLiveData.observe((PropertyChangeEvent evt) -> {
            List<FileModel> fileModels = (List<FileModel>) evt.getNewValue();
            jPanelFiles.removeAll();
            for (FileModel fileModel : fileModels) {
                jPanelFiles.add(new FileItem(fileModel));
            }
            jPanelFiles.revalidate();
            jPanelFiles.repaint();
        });

        ClientAPI.getSocket().on(Socket.EVENT_CONNECT, (Object... os) -> {
            new NotificationDialog("متصل مع المخدم", NotificationDialog.INFO, 1500).setVisible(true);
        });
        ClientAPI.getSocket().on(Socket.EVENT_DISCONNECT, (Object... os) -> {
            new NotificationDialog("انقطع الاتصال مع المخدم", NotificationDialog.ERORR, 2000).setVisible(true);
        });

        ClientAPI.getSocket().on("update", (Object... os) -> {
            if (os.length > 0) {
                Integer message = (Integer) os[0];
                if (message == this.userModel.id) {
                    mainViewModel.get_receive_files();
                    new NotificationDialog("تم استلام ملف جديد", NotificationDialog.INFO, 2000).setVisible(true);
                }
            }
        });

        ClientAPI.getSocket().connect();

        mainViewModel.get_receive_files();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mainPar = new org.jdesktop.swingx.JXPanel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelFiles = new javax.swing.JPanel();
        fileItem1 = new ui.MainJFrame.FileItem();
        fileItem2 = new ui.MainJFrame.FileItem();
        fileItem3 = new ui.MainJFrame.FileItem();
        fileItem4 = new ui.MainJFrame.FileItem();
        jClock1 = new data.JClock();
        cusButton1 = new data.CusButton();
        cusButton2 = new data.CusButton();
        stateParProgress = new org.jdesktop.swingx.JXBusyLabel();
        stateParMsg = new javax.swing.JLabel();
        cusButton3 = new data.CusButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("user name");

        jLabel2.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("account type");

        mainPar.setBackground(data.MyColor.BackColor);
        mainPar.setAlignmentX(0.0F);
        mainPar.setAlignmentY(0.0F);
        mainPar.setFocusable(false);
        mainPar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mainParMouseDragged(evt);
            }
        });
        mainPar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainParMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainParMousePressed(evt);
            }
        });

        jXLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel3.setText("الواجهة الرئيسية");
        jXLabel3.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-square-32.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-30.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-close-window-32.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        mainPar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout mainParLayout = new javax.swing.GroupLayout(mainPar);
        mainPar.setLayout(mainParLayout);
        mainParLayout.setHorizontalGroup(
            mainParLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainParLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(7, 7, 7))
        );
        mainParLayout.setVerticalGroup(
            mainParLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainParLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainParLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(mainParLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainParLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "الملفات المستلمة", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DIN Next LT Arabic", 0, 15))); // NOI18N

        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(5);
        jPanelFiles.setLayout(verticalLayout1);
        jPanelFiles.add(fileItem1);
        jPanelFiles.add(fileItem2);
        jPanelFiles.add(fileItem3);
        jPanelFiles.add(fileItem4);

        jScrollPane1.setViewportView(jPanelFiles);

        cusButton1.setForeground(new java.awt.Color(255, 255, 255));
        cusButton1.setText("الملفات المستلمة");
        cusButton1.setColor(data.MyColor.Red);
        cusButton1.setColorClick(data.MyColor.Red);
        cusButton1.setFocusPainted(false);
        cusButton1.setFocusable(false);
        cusButton1.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 15)); // NOI18N
        cusButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cusButton1.setRadius(25);
        cusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusButton1ActionPerformed(evt);
            }
        });

        cusButton2.setForeground(new java.awt.Color(255, 255, 255));
        cusButton2.setText("ارسال ملف");
        cusButton2.setColor(data.MyColor.BackColor);
        cusButton2.setColorClick(data.MyColor.BackColor);
        cusButton2.setFocusPainted(false);
        cusButton2.setFocusable(false);
        cusButton2.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 15)); // NOI18N
        cusButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cusButton2.setRadius(25);
        cusButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusButton2ActionPerformed(evt);
            }
        });

        stateParProgress.setForeground(new java.awt.Color(255, 255, 255));
        stateParProgress.setBusy(true);
        stateParProgress.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 16)); // NOI18N

        stateParMsg.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 16)); // NOI18N
        stateParMsg.setForeground(new java.awt.Color(51, 51, 51));
        stateParMsg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stateParMsg.setText("جاهز");

        cusButton3.setForeground(new java.awt.Color(255, 255, 255));
        cusButton3.setText("الملفات المرسلة");
        cusButton3.setColor(data.MyColor.Blue);
        cusButton3.setColorClick(data.MyColor.Blue);
        cusButton3.setFocusPainted(false);
        cusButton3.setFocusable(false);
        cusButton3.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 15)); // NOI18N
        cusButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cusButton3.setRadius(25);
        cusButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jClock1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(stateParMsg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(stateParProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClock1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cusButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cusButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cusButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stateParMsg)
                            .addComponent(stateParProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                .addContainerGap())
        );

        stateParProgress.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() == JFrame.MAXIMIZED_BOTH)
            this.setExtendedState(JFrame.NORMAL);
        else
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (data.JOptionContiuneDialog.showConfirmDialog(this) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void mainParMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainParMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_mainParMouseDragged

    private void mainParMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainParMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            if (this.getExtendedState() == JFrame.MAXIMIZED_BOTH) {
                this.setExtendedState(JFrame.NORMAL);
            } else {
                this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
            //handle double click event.
        }
    }//GEN-LAST:event_mainParMouseClicked

    private void mainParMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainParMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mainParMousePressed

    private void cusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusButton1ActionPerformed
        // TODO add your handling code here:
        if (!mainViewModel.working.getValue().isRunning()) {
            mainViewModel.get_receive_files();
        }

    }//GEN-LAST:event_cusButton1ActionPerformed

    private void cusButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusButton2ActionPerformed
        // TODO add your handling code here:
        SendFileJDialog.showDialog(this);
    }//GEN-LAST:event_cusButton2ActionPerformed

    private void cusButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusButton3ActionPerformed
        // TODO add your handling code here:
        FileSendJDialog.showDialog(this);
    }//GEN-LAST:event_cusButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private data.CusButton cusButton1;
    private data.CusButton cusButton2;
    private data.CusButton cusButton3;
    private ui.MainJFrame.FileItem fileItem1;
    private ui.MainJFrame.FileItem fileItem2;
    private ui.MainJFrame.FileItem fileItem3;
    private ui.MainJFrame.FileItem fileItem4;
    private data.JClock jClock1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelFiles;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXPanel mainPar;
    private javax.swing.JLabel stateParMsg;
    private org.jdesktop.swingx.JXBusyLabel stateParProgress;
    // End of variables declaration//GEN-END:variables
}
