/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.FileSendJDialog;

import java.awt.ComponentOrientation;
import java.awt.Insets;
import java.util.List;
import javax.swing.JCheckBox;
import model.FileSendModel;
import model.UserModel;

/**
 *
 * @author ahmad
 */
public class FileSendItem extends javax.swing.JPanel {

    private FileSendModel fileModel;

    public FileSendItem() {
        initComponents();
        jPanelUsers.removeAll();
        jPanelUsers.revalidate();
        jPanelUsers.repaint();
    }

    public FileSendItem(FileSendModel fileModel) {
        initComponents();
        this.fileModel = fileModel;

        jPanelUsers.removeAll();
        jPanelUsers.revalidate();
        jPanelUsers.repaint();

        if (this.fileModel != null) {
            jLabelName.setText(fileModel.file_name);
            jLabelSender.setText(fileModel.extension);
            jLabelSize.setText(fileModel.file_size + " بايت");
            jLabelName.setText(fileModel.file_name);
            jLabelDate.setText(fileModel.getCreateDate());
            
            List<FileSendModel.User> users = this.fileModel.users;
            jPanelUsers.removeAll();
            for (FileSendModel.User user : users) {
                JCheckBox cc = new JCheckBox();
                cc.setText(user.user_name + " (" + user.center_name + ")");
                cc.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
                cc.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 15));
                cc.setMargin(new Insets(5, 10, 5, 10));
                cc.setSelected(user.isReciver());
                cc.setEnabled(false);
                jPanelUsers.add(cc);
            }
            jPanelUsers.revalidate();
            jPanelUsers.repaint();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelSender = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelUsers = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-file-100.png"))); // NOI18N

        jLabelName.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 20)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelName.setText("اسم الملف");

        jLabelSender.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelSender.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSender.setText("نوع الملف");

        jLabelSize.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSize.setText("حجم الملف");

        jLabelDate.setFont(new java.awt.Font("DIN Next LT Arabic", 1, 18)); // NOI18N
        jLabelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDate.setText("تاريخ");

        jPanelUsers.setLayout(new org.jdesktop.swingx.HorizontalLayout());

        jCheckBox1.setText("jCheckBox1");
        jPanelUsers.add(jCheckBox1);

        jCheckBox2.setText("jCheckBox2");
        jPanelUsers.add(jCheckBox2);

        jCheckBox3.setText("jCheckBox3");
        jPanelUsers.add(jCheckBox3);

        jPanelUsers.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        jScrollPane1.setViewportView(jPanelUsers);
        jScrollPane1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabelSize, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSender, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSender)
                            .addComponent(jLabelSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate)))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSender;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JPanel jPanelUsers;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
