/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.FileSendJDialog;

import data.Working;
import java.awt.Component;
import java.beans.PropertyChangeEvent;
import java.util.List;
import javax.swing.JOptionPane;
import model.FileModel;
import ui.MainJFrame.MainViewModel;

/**
 *
 * @author ahmad
 */
public class FileSendJDialog extends javax.swing.JDialog {

    private int x, y;
    private int dialogResult;
    private MainViewModel mainViewModel;

    /**
     * Creates new form SendJDialog
     */
    public FileSendJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.dialogResult = JOptionPane.DEFAULT_OPTION;

        jPanelFiles.removeAll();
        jPanelFiles.revalidate();
        jPanelFiles.repaint();

        this.mainViewModel = new MainViewModel();

        mainViewModel.working.observe((PropertyChangeEvent evt) -> {
            Working working = (Working) evt.getNewValue();
            stateParProgress.setBusy(working.isRunning());
            stateParProgress.setVisible(working.isRunning());
            stateParMsg.setText(working.getsSmg());
            stateParMsg.setForeground(working.getColor());
        });
        
        mainViewModel.filesSendLiveData.observe((PropertyChangeEvent evt) -> {
            List<FileModel> fileModels = (List<FileModel>) evt.getNewValue();
            jPanelFiles.removeAll();
            for (FileModel fileModel : fileModels) {
                jPanelFiles.add(new FileSendItem(fileModel));
            }
            jPanelFiles.revalidate();
            jPanelFiles.repaint();
        });
        
        mainViewModel.get_send_files();

    }

    public static int showDialog(Component parentComponent) {
        FileSendJDialog d = new FileSendJDialog((javax.swing.JFrame) parentComponent, true);
        d.setVisible(true);
        return d.dialogResult;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelFiles = new javax.swing.JPanel();
        fileSendItem1 = new ui.FileSendJDialog.FileSendItem();
        fileSendItem2 = new ui.FileSendJDialog.FileSendItem();
        stateParProgress = new org.jdesktop.swingx.JXBusyLabel();
        stateParMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(data.MyColor.BackColor);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-close-window-32.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jXLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel3.setText("الملفات المرسلة");
        jXLabel3.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "الملفات المرسلة", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DIN Next LT Arabic", 0, 15))); // NOI18N

        org.jdesktop.swingx.VerticalLayout verticalLayout2 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout2.setGap(5);
        jPanelFiles.setLayout(verticalLayout2);
        jPanelFiles.add(fileSendItem1);
        jPanelFiles.add(fileSendItem2);

        jScrollPane1.setViewportView(jPanelFiles);

        stateParProgress.setForeground(new java.awt.Color(255, 255, 255));
        stateParProgress.setBusy(true);
        stateParProgress.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 16)); // NOI18N

        stateParMsg.setFont(new java.awt.Font("DIN Next LT Arabic", 0, 16)); // NOI18N
        stateParMsg.setForeground(new java.awt.Color(51, 51, 51));
        stateParMsg.setText("جاهز");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stateParMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateParProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateParProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateParMsg))
                .addContainerGap())
        );

        stateParProgress.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        dialogResult = JOptionPane.NO_OPTION;
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.FileSendJDialog.FileSendItem fileSendItem1;
    private ui.FileSendJDialog.FileSendItem fileSendItem2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFiles;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private javax.swing.JLabel stateParMsg;
    private org.jdesktop.swingx.JXBusyLabel stateParProgress;
    // End of variables declaration//GEN-END:variables
}
